title: Things I like to Share
email: anupvarghese@gmail.com
description: >
  Things I do & Things I like to Share
baseurl: ""
url: "https://anupvarghese.github.io"
author: anupvarghese
twitter_username: anupvarghese
github_username:  anupvarghese
google_analytics: UA-72042804-1
disqus:
  shortname: anupvarghese
# Build settings
markdown: kramdown

theme: minima
gems:
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
